import ArbiterVildred from "../images/hero-avatar/ArbiterVildred.png";
import MaidChole from "../images/hero-avatar/MaidChole.png";
import AdventurerRas from "../images/hero-avatar/AdventurerRas.png";
import SeasideBellona from "../images/hero-avatar/SeasideBellona.png";
import Vivian from "../images/hero-avatar/Vivian.png";
import InfernoKhawazu from "../images/hero-avatar/InfernoKhawazu.png";
import Rem from "../images/hero-avatar/Rem.png";
import Violet from "../images/hero-avatar/Violet.png";
import RoamingWarriorLeo from "../images/hero-avatar/RoamingWarriorLeo.png";
import AngeloflightAngelica from "../images/hero-avatar/AngeloflightAngelica.png";
import Hasol from "../images/hero-avatar/Hasol.png";
import Tamarinne from "../images/hero-avatar/Tamarinne.png";
import Landy from "../images/hero-avatar/Landy.png";
import Krau from "../images/hero-avatar/Krau.png";
import GeneralPurrgis from "../images/hero-avatar/GeneralPurrgis.png";
import Milim from "../images/hero-avatar/Milim.png";
import Lots from "../images/hero-avatar/Lots.png";
import Penelope from "../images/hero-avatar/Penelope.png";
import SummertimeIseria from "../images/hero-avatar/SummertimeIseria.png";
import Ainos from "../images/hero-avatar/Ainos.png";
import TempestSurin from "../images/hero-avatar/TempestSurin.png";
import Armin from "../images/hero-avatar/Armin.png";
import Mistychain from "../images/hero-avatar/Mistychain.png";
import Ains from "../images/hero-avatar/Ains.png";
import Belian from "../images/hero-avatar/Belian.png";
import SpecterTenebria from "../images/hero-avatar/SpecterTenebria.png";
import Peira from "../images/hero-avatar/Peira.png";
import Jacko from "../images/hero-avatar/Jacko.png";
import Celeste from "../images/hero-avatar/Celeste.png";
import Diene from "../images/hero-avatar/Diene.png";

export const heroSearchData = [
  {
    id: 0,
    heroName: "執行官維德瑞",
    image: ArbiterVildred,
    stars: 5,
    attributes: "dark",
    profession: "Thief",
    specialEffect: ["復活", "速攻值減少"],
    specialBuff: ["無特殊buff"],
    buff: ["無buff"],
    debuff: ["命中率減少"],
  },
  {
    id: 1,
    heroName: "僕人克蘿愛",
    image: MaidChole,
    stars: 5,
    attributes: "light",
    profession: "Soul Weaver",
    specialEffect: ["復活", "解除弱化效果"],
    specialBuff: ["無特殊buff"],
    buff: ["攻擊力增加", "甦醒"],
    debuff: ["暈眩"],
  },
  {
    id: 2,
    heroName: "冒險家拉斯",
    image: AdventurerRas,
    stars: 3,
    attributes: "fire",
    profession: "Knight",
    specialEffect: ["解除強化效果"],
    specialBuff: ["無特殊buff"],
    buff: ["防禦力增加", "免疫"],
    debuff: ["防禦力減少"],
  },
  {
    id: 3,
    heroName: "海邊的維爾蘿娜",
    image: SeasideBellona,
    stars: 5,
    attributes: "water",
    profession: "Ranger",
    specialEffect: ["無特殊效果"],
    specialBuff: ["無特殊buff"],
    buff: ["無buff"],
    debuff: ["標靶", "防禦力減少", "無法獲得強化效果", "無法恢復"],
  },
  {
    id: 4,
    heroName: "薇薇安",
    image: Vivian,
    stars: 5,
    attributes: "earth",
    profession: "Mage",
    specialEffect: ["速攻值增加"],
    specialBuff: ["無特殊buff"],
    buff: ["攻擊力增加", "攻擊力大幅增加", "免疫"],
    debuff: ["無debuff"],
  },
  {
    id: 5,
    heroName: "烈焰的卡瓦朱",
    image: InfernoKhawazu,
    stars: 4,
    attributes: "dark",
    profession: "Warrior",
    specialEffect: ["速攻值增加", "解除強化效果", "解除弱化效果", "激爆"],
    specialBuff: ["魄力"],
    buff: ["無buff"],
    debuff: ["燒傷"],
  },
  {
    id: 6,
    heroName: "雷姆",
    image: Rem,
    stars: 5,
    attributes: "water",
    profession: "Warrior",
    specialEffect: ["解除強化效果", "速攻值增加"],
    specialBuff: ["鬼化"],
    buff: ["攻擊力增加"],
    debuff: ["防禦力減少", "命中率減少", "無法恢復"],
  },
  {
    id: 7,
    heroName: "菲奧雷托",
    image: Violet,
    stars: 5,
    attributes: "earth",
    profession: "Thief",
    specialEffect: ["速攻值增加", "解除弱化效果", "追加回合"],
    specialBuff: ["識破"],
    buff: ["無buff"],
    debuff: ["攻擊力減少"],
  },
  {
    id: 8,
    heroName: "流浪勇士雷歐",
    image: RoamingWarriorLeo,
    stars: 4,
    attributes: "dark",
    profession: "Ranger",
    specialEffect: ["激爆"],
    specialBuff: ["無特殊buff"],
    buff: ["技能傷害無效"],
    debuff: ["攻擊力減少", "防禦力減少", "炸彈", "速度下降"],
  },
  {
    id: 9,
    heroName: "光之天使安潔莉卡",
    image: AngeloflightAngelica,
    stars: 4,
    attributes: "light",
    profession: "Mage",
    specialEffect: ["速攻值減少", "速攻值增加", "解除弱化效果", "解除強化效果"],
    specialBuff: ["無特殊buff"],
    buff: ["技能傷害無效"],
    debuff: ["沉默", "無法獲得強化效果"],
  },
  {
    id: 10,
    heroName: "夏率",
    image: Hasol,
    stars: 3,
    attributes: "dark",
    profession: "Knight",
    specialEffect: ["速攻值增加"],
    specialBuff: ["無特殊buff"],
    buff: ["防禦力增加", "速度提升"],
    debuff: ["無debuff"],
  },
  {
    id: 11,
    heroName: "塔瑪林爾",
    image: Tamarinne,
    stars: 5,
    attributes: "fire",
    profession: "Soul Weaver",
    specialEffect: [
      "解除強化效果",
      "夾攻",
      "速攻值增加",
      "解除弱化效果",
      "追加回合",
    ],
    specialBuff: ["歌姬"],
    buff: ["攻擊力增加"],
    debuff: ["無debuff"],
  },
  {
    id: 12,
    heroName: "蘭蒂",
    image: Landy,
    stars: 5,
    attributes: "earth",
    profession: "Ranger",
    specialEffect: ["速攻值增加", "無法反擊", "貫穿"],
    specialBuff: ["無特殊buff"],
    buff: ["速度提升"],
    debuff: ["無debuff"],
  },
  {
    id: 13,
    heroName: "克勞烏",
    image: Krau,
    stars: 5,
    attributes: "water",
    profession: "Knight",
    specialEffect: ["速攻值減少", "貫穿"],
    specialBuff: ["無特殊buff"],
    buff: ["防禦力增加", "防護罩"],
    debuff: ["挑釁"],
  },
  {
    id: 14,
    heroName: "大將法濟斯",
    image: GeneralPurrgis,
    stars: 4,
    attributes: "light",
    profession: "Warrior",
    specialEffect: ["速攻值增加"],
    specialBuff: ["無特殊buff"],
    buff: ["攻擊力增加"],
    debuff: ["挑釁", "暈眩"],
  },
  {
    id: 15,
    heroName: "蜜莉姆",
    image: Milim,
    stars: 5,
    attributes: "fire",
    profession: "Mage",
    specialEffect: ["減少靈魂", "滅亡"],
    specialBuff: ["龍眼"],
    buff: ["攻擊力增加", "迴避增加"],
    debuff: ["無debuff"],
  },
  {
    id: 16,
    heroName: "拉茲",
    image: Lots,
    stars: 4,
    attributes: "earth",
    profession: "Soul Weaver",
    specialEffect: ["速攻值增加"],
    specialBuff: ["無特殊buff"],
    buff: ["持續恢復"],
    debuff: ["攻擊力減少"],
  },
  {
    id: 17,
    heroName: "潘尼羅佩",
    image: Penelope,
    stars: 3,
    attributes: "dark",
    profession: "Thief",
    specialEffect: ["速攻值增加", "追加回合", "資源減少"],
    specialBuff: ["無特殊buff"],
    buff: ["防護罩", "隱身"],
    debuff: ["攻擊力減少", "暈眩"],
  },
  {
    id: 18,
    heroName: "南國的伊賽麗亞",
    image: SummertimeIseria,
    stars: 5,
    attributes: "fire",
    profession: "Ranger",
    specialEffect: ["解除強化效果", "速攻值增加", "激爆"],
    specialBuff: ["無特殊buff"],
    buff: ["速度提升"],
    debuff: ["炸彈", "攻擊力減少"],
  },
  {
    id: 19,
    heroName: "艾諾斯",
    image: Ainos,
    stars: 3,
    attributes: "dark",
    profession: "Soul Weaver",
    specialEffect: ["速攻值增加", "解除弱化效果"],
    specialBuff: ["無特殊buff"],
    buff: ["攻擊力增加", "速度提升"],
    debuff: ["防禦力減少"],
  },
  {
    id: 20,
    heroName: "風雲蘇琳",
    image: TempestSurin,
    stars: 4,
    attributes: "light",
    profession: "Thief",
    specialEffect: ["速攻值增加"],
    specialBuff: ["無特殊buff"],
    buff: ["隱身"],
    debuff: ["出血", "無法獲得強化效果", "沉默"],
  },
  {
    id: 21,
    heroName: "亞敏",
    image: Armin,
    stars: 4,
    attributes: "earth",
    profession: "Knight",
    specialEffect: ["解除弱化效果"],
    specialBuff: ["無特殊buff"],
    buff: ["防禦力增加", "防護罩"],
    debuff: ["暈眩"],
  },
  {
    id: 22,
    heroName: "美絲緹彩",
    image: Mistychain,
    stars: 3,
    attributes: "water",
    profession: "Mage",
    specialEffect: ["無特殊效果"],
    specialBuff: ["無特殊buff"],
    buff: ["甦醒"],
    debuff: ["無法恢復", "攻擊力減少"],
  },
  {
    id: 23,
    heroName: "艾因茲",
    image: Ains,
    stars: 3,
    attributes: "earth",
    profession: "Warrior",
    specialEffect: ["無特殊效果"],
    specialBuff: ["無特殊buff"],
    buff: ["無buff"],
    debuff: ["暈眩"],
  },
  {
    id: 24,
    heroName: "伯里安",
    image: Belian,
    stars: 5,
    attributes: "light",
    profession: "Knight",
    specialEffect: ["解除強化效果", "無法獲得靈魂", "速攻值減少"],
    specialBuff: ["無特殊buff"],
    buff: ["效果命中增加", "暴擊率增加", "持續恢復", "防禦力增加"],
    debuff: ["速度下降", "命中率減少", "挑釁"],
  },
  {
    id: 25,
    heroName: "幻影的泰妮布里雅",
    image: SpecterTenebria,
    stars: 5,
    attributes: "dark",
    profession: "Mage",
    specialEffect: ["無法反擊", "速攻值減少"],
    specialBuff: ["無特殊buff"],
    buff: ["無buff"],
    debuff: ["中毒", "暈眩"],
  },
  {
    id: 26,
    heroName: "沛伊拉",
    image: Peira,
    stars: 5,
    attributes: "water",
    profession: "Thief",
    specialEffect: ["追加回合"],
    specialBuff: ["無特殊buff"],
    buff: ["攻擊力增加", "隱身", "護衛", "防護罩"],
    debuff: ["暈眩", "束縛", "無法獲得強化效果"],
  },
  {
    id: 27,
    heroName: "潔克歐",
    image: Jacko,
    stars: 5,
    attributes: "fire",
    profession: "Warrior",
    specialEffect: ["速攻值增加", "追加回合", "貫穿"],
    specialBuff: ["喀戎之鎖"],
    buff: ["隱身", "攻擊力增加"],
    debuff: ["暈眩"],
  },
  {
    id: 28,
    heroName: "賽雷斯特",
    image: Celeste,
    stars: 3,
    attributes: "light",
    profession: "Ranger",
    specialEffect: ["速攻值減少", "追加回合"],
    specialBuff: ["無特殊buff"],
    buff: ["攻擊力增加"],
    debuff: ["命中率減少"],
  },
  {
    id: 29,
    heroName: "迪埃妮",
    image: Diene,
    stars: 5,
    attributes: "water",
    profession: "Soul Weaver",
    specialEffect: ["速攻值增加", "解除弱化效果"],
    specialBuff: ["無特殊buff"],
    buff: ["防護罩", "攻擊力增加", "暴擊抗性增加"],
    debuff: ["無debuff"],
  },
];
